from django.urls import path
from myapp import views

urlpatterns = [
    # LOGIN
    path('login_post/', views.login_post),
    path('login_get/', views.login_get),
    path('logout_get', views.logout_get),
    path('login_/', views.login_),

    # ADMIN
    path('adminhome/', views.adminhome),
    path('admin_generate_report/', views.admin_generate_report),

    path('Approve_shop/<shop_id>', views.Approve_shop),
    path('Reject_shop/<shop_id>', views.Reject_shop),
    path('view_shop/', views.view_shop),
    path('view_cutomer/', views.view_cutomer),
    path('view_approved_shop/', views.view_approved_shop),
    path('view_Rejected_shop/', views.view_Rejected_shop),
    path('view_complaint/', views.view_complaint),
    path('send_reply/', views.send_reply),
    path('send_reply_get/<cus_id>', views.send_reply_get),
    path('change_password_admin/', views.change_password_admin),
    path('change_password_admin_post/', views.change_password_admin_post),
    path('view_rating_review/', views.view_rating_review),
    path('view_approved_and_rejected/', views.view_approved_and_rejected),
    path('check_staff_exists/', views.check_staff_exists),
    path('add_pet_type_get/', views.add_pet_type_get),
    path('add_pet_post/', views.add_pet_post),
    path('add_category_post/', views.add_category_post),
    path('add_product_get/', views.add_product_get),
    path('add_product_post/', views.add_product_post),
    path('edit_product_get/<pro_id>', views.edit_product_get),
    path('edit_product_post/', views.edit_product_post),
    path('delete_product/<pro_id>', views.delete_product),
    path('View_product/', views.View_product),
    path('add_grooming_get/', views.add_grooming_get),
    path('add_grooming_post/', views.add_grooming_post),
    path('view_grooming/', views.view_grooming),
    path('view_delivery_address/', views.view_delivery_address),
    path('edit_grooming_services_get/<groom_id>', views.edit_grooming_services_get),
    path('edit_grooming_services_post/', views.edit_grooming_services_post),
    path('delete_groomigs_service/<groom_id>', views.delete_groomigs_service),

    # SHOP
    path('Staff_registration_get/', views.Staff_registration_get),
    path('Staff_registration_Post/', views.Staff_registration_Post),
    path('shophome/', views.shophome),
    path('change_password_shop_get/', views.change_password_shop_get),
    path('change_password_shop_post/', views.change_password_shop_post),
    path('add_category_get/', views.add_category_get),
    path('view_product_get/', views.view_product_get),

    path('update_Product_availabilty_get/<pro_id>', views.update_Product_availabilty_get),
    path('update_Product_availabilty_post/', views.update_Product_availabilty_post),
    path('update_product_quantity/', views.update_product_quantity),
    path('view_profile_shop/', views.view_profile_shop),
    path('Staff_view_orders/', views.Staff_view_orders),
    path('staff_view_payments/', views.staff_view_payments),
    path('staff_generate_report/', views.staff_generate_report),
    path('shop_view_order_items/<oid>/', views.shop_view_order_items),
    path('edit_profile_get/<shop_id>', views.edit_profile_get),
    path('edit_profile_shop_post/', views.edit_profile_shop_post),
    path('update_order_status_arrow/<oid>/<action>/', views.update_order_status_arrow),

    path('staff_view_reviews/', views.staff_view_reviews),
    path('staff_view_complaints/', views.staff_view_complaints),
    path('view_grooming_booking/', views.view_grooming_booking),
    path('view_groomings_get/', views.view_groomings_get),
    path('update_booking_post/', views.update_booking_post),
    path('update_booking_get/<gb_id>', views.update_booking_get),
    path('accepted_booking/<gb_id>', views.accepted_booking),
    path('rejected_booking/<gb_id>', views.rejected_booking),

    # user______________________________________________________________________________________________________________

    path("view_groomings/", views.view_groomings),
    path("view_products/", views.view_products),
    path("add_cart/", views.add_cart),
    path("view_cart/", views.view_cart),
    path("book_grooming/", views.book_grooming),
    path("add_complaint/", views.add_complaint),
    path("view_complaints/", views.view_complaints),
    path("view_staff/", views.view_staff),

    # path("buy_product/", views.buy_product),
    path('user_order_history/', views.user_order_history),
    path("add_product_review/", views.add_product_review),
    path("view_reviews/", views.view_reviews),
    # path("shop_details/", views.shop_details),
    path("search_shops/", views.search_shops),
    # path("send_message/", views.send_message),
    # path("get_messages/", views.get_messages),
    path("view_profile/", views.view_profile),
    path("update_profile/", views.update_profile),
    path("filter_shops/", views.filter_shops),
    path("user_signuppost/", views.user_signuppost),
    path("deletefromcart/", views.deletefromcart),
    path("cartpayment/", views.cartpayment),
    path("add_address/", views.add_address),
    path("get_addresses/", views.get_addresses),
    path("set_default_address/", views.set_default_address),
    path('update_cart_quantity/', views.update_cart_quantity),
    path('view_pet_types/', views.view_pet_types),
    path('view_booking/', views.view_booking),
    path('filter_groomers/', views.filter_groomers),
    path('change_password/', views.change_password),
    path('logout_user/', views.logout_user),
    path("toggle_wishlist/", views.toggle_wishlist),
    path("view_wishlist/", views.view_wishlist),

    # Public
    path("public_home/", views.public_home),

]
